i_triad_cliente:
    resource: "@iTriadBundle/Controller/ClienteController.php"
    type:     annotation

i_triad_projeto:
    resource: "@iTriadBundle/Controller/ProjetoController.php"
    type:     annotation

i_triad_orcamento:
    resource: "@iTriadBundle/Controller/OrcamentoController.php"
    type:     annotation

i_triad_funcionario:
    resource: "@iTriadBundle/Controller/FuncionarioController.php"
    type:     annotation

i_triad_status:
    resource: "@iTriadBundle/Controller/StatusController.php"
    type:     annotation

i_triad:
    resource: "@iTriadBundle/Resources/config/routing.php"
    prefix:   /