<?php

namespace iTriadBundle\Repository;

/**
 * OrcamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrcamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
